# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pierce Darragh
author: Pierce Darragh
email: pierce.darragh@gmail.com
description: >
  Just a blog for helping me keep my thoughts organized.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pdarragh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: pdarragh

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
permalink: /blog/:year/:month/:day/:title/

# The solution for building category pages came from:
#  https://kylewbanks.com/blog/creating-category-pages-in-jekyll-without-plugins
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

# Other settings
minima:
  date_format: "%b %e, %Y at %I:%M%P"
disqus:
  shortname: pdarragh
google_analytics: UA-99177722-1
